function f = ode_double_pend(in1,in2,in3)
%ODE_DOUBLE_PEND
%    F = ODE_DOUBLE_PEND(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    05-Apr-2023 11:33:05

Mu1 = in2(1,:);
Mu2 = in2(2,:);
bin = in3(8,:);
d1 = in3(5,:);
d2 = in3(6,:);
g = in3(7,:);
l1 = in3(1,:);
l2 = in3(2,:);
m1 = in3(3,:);
m2 = in3(4,:);
phi1 = in1(1,:);
phi2 = in1(2,:);
phi1p = in1(3,:);
phi2p = in1(4,:);
t2 = sin(phi1);
t3 = sin(phi2);
t4 = l1.^2;
t5 = l2.^2;
t6 = m2.^2;
t7 = phi1.*2.0;
t8 = phi2.*2.0;
t9 = phi1p.^2;
t10 = phi2p.^2;
t11 = -phi2;
t12 = -t8;
t13 = phi1+t11;
t16 = t7+t11;
t14 = cos(t13);
t15 = sin(t13);
t17 = t7+t12;
t18 = sin(t16);
t19 = sin(t17);
mt1 = [phi1p;phi2p;(Mu1.*l2.*4.0-Mu2.*l1.*t14.*2.0-d1.*l2.*phi1p.*4.0-d2.*l2.*phi1p.*4.0+d2.*l2.*phi2p.*4.0-d2.*l1.*phi1p.*t14.*2.0+d2.*l1.*phi2p.*t14.*2.0+g.*l1.*l2.*m1.*t2.*4.0+g.*l1.*l2.*m2.*t2.*3.0+g.*l1.*l2.*m2.*sin(phi1+t12)-bin.*l1.*m2.*t5.*t10.*t15.*4.0-bin.*l2.*m2.*t4.*t9.*t19)./(l2.*t4.*(m1.*4.0+m2.*2.0-m2.*t14.^2).*2.0)];
mt2 = [(Mu2.*l1.*m1.*4.0+Mu2.*l1.*m2.*2.0+d2.*l1.*m1.*phi1p.*4.0-d2.*l1.*m1.*phi2p.*4.0+d2.*l1.*m2.*phi1p.*2.0-d2.*l1.*m2.*phi2p.*2.0-Mu1.*l2.*m2.*t14.*2.0+d1.*l2.*m2.*phi1p.*t14.*2.0+d2.*l2.*m2.*phi1p.*t14.*2.0-d2.*l2.*m2.*phi2p.*t14.*2.0+g.*l1.*l2.*t3.*t6-g.*l1.*l2.*t6.*t18+g.*l1.*l2.*m1.*m2.*t3.*3.0-g.*l1.*l2.*m1.*m2.*t18+bin.*l2.*t4.*t6.*t9.*t15.*2.0+bin.*l1.*t5.*t6.*t10.*t19+bin.*l2.*m1.*m2.*t4.*t9.*t15.*4.0)./(l1.*m2.*t5.*(m1.*8.0+m2.*3.0-m2.*cos(t17)))];
f = [mt1;mt2];
